# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efb7702891b2d55e8483dd286285b9bd6de2fd5880c4390e93215345262477f5d25c446af7562be796973201e50fb7f4501173542ac072679a8645b9b49999bb

test:
  secret_key_base: ccb54a90b7c41620d7ccf20f59c47d8e811e6e46cf474dbdefdaa62c6b11b817b90579c660d868e6fe1a864744f0b03603d5070094f554e6fb54ee26171583bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
